---
# basic packages
- name: Install Emacs
  yum: name=emacs state=present
- name: pause 3 seconds
  pause: seconds=3
  when: '"development" not in group_names'
- name: Install Git
  yum: name=git state=present
