---
- name: latest scientific linux
  yum: name=yum-conf-sl7x state=present
- name: latest SL repos
  yum: name=yum-conf-repos state=present
- name: install epel repository
  yum: name=yum-conf-epel state=present
- name: install libxml-devel
  yum: name=libxml2-devel state=latest
- name: install libxlst-devel
  yum: name=libxslt-devel state=latest
