---
# basic packages
- name: install python
  yum: name=python state=present
- name: pause 3 seconds
  pause: seconds=3
  when: '"development" not in group_names'
- name: install python-devel
  yum: name=python-devel state=present
- name: pause 3 seconds
  pause: seconds=3
  when: '"development" not in group_names'
- name: install python-pip
  yum: name=python-pip state=latest
- name: pause 3 seconds
  pause: seconds=3
  when: '"development" not in group_names'
- name: install python-virtualenv
  yum: name=python-virtualenv state=latest
